trigger:
- main

pool:
  name: self-hosted

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '14.x'
      displayName: 'Install Node.js'

    - script: npm install
      displayName: 'Install dependencies'

    - script: npm run build
      displayName: 'Build application'
    
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(build.artifactstagingdirectory)/node-app.zip'
      displayName: 'Archive files'

    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: '$(build.artifactstagingdirectory)'
        artifactName: 'node-app-artifact'
        publishLocation: 'Container'

- stage: Test
  jobs:
  - job: TestJob
    steps:
    - script: npm install
      displayName: 'Install dependencies for testing'

    - script: npm test
      displayName: 'Run unit tests'
